/* AUTOGENERATED DO NOT MODIFY */

/**
  ******************************************************************************
  * @file    network.c
  * @brief   NN Code autogenerated DO NOT MODIFY IT
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2023 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/*
 * GIT_SHA         "7cc654104236b2ac726c804c5d7f201e2afd1c79"
 * GIT_BRANCH      "HEAD"
 * GIT_DESCRIPTION "STAI-3.0.0-254-g7cc654104"
 *
 * Command Line options:
 * --load-mdesc-file = "D:/STAI/4.0/Utilities/configs/stm32n6"
 * --load-cdesc-file = "D:/STAI/4.0/Utilities/configs/cortex-m55"
 * --load-mpool-file = "C:/Users/kth59/.stm32cubeaistudio/workspace/ANN_GMPPT/.ai/memory_pool"
 * --cache-maintenance = true
 * --enable-virtual-mem-pools = true
 * --native-float = true
 * --json-quant-file = "C:/Users/kth59/.stm32cubeaistudio/workspace/ANN_GMPPT/.ai/st_ai_output/gmpp_model_int8_OE_3_3_1_Q.json"
 * --Os = true
 * --Ocache-opt = true
 * --enable-epoch-controller = true
 * --output-info-file = "c_info"
 * --onnx-input = "C:/Users/kth59/.stm32cubeaistudio/workspace/ANN_GMPPT/.ai/st_ai_output/gmpp_model_int8_OE_3_3_1.onnx"
 * --out-dir-prefix = "C:/Users/kth59/.stm32cubeaistudio/workspace/ANN_GMPPT/.ai/st_ai_ws/neural_art__network/"
 * --network-name = "network"
 * --generate-stai = true
 * --Oauto-sched = true
 *
 * auto* option expanded into:
 *   alt-scheduler = false
 */

#include "ll_aton_NN_interface.h"
#include "ll_aton.h"
#include "ll_aton_lib.h"
#include "ll_aton_version.h"
#include "ll_sw.h"
#include "ecloader.h"
#include "ll_aton_cipher.h"

#if LL_ATON_VERSION_MAJOR != 1 || LL_ATON_VERSION_MINOR != 1 || LL_ATON_VERSION_MICRO != 3 || LL_ATON_VERSION_DEV != 262
#  error "Possible mismatch in ll_aton library used"
#endif

#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#  define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

/* global pool 8 is 1.03 KB */
/* index=8 file postfix=xSPI2 name=octoFlash offset=0x71000000  relative_mode size=117440512 READ_ONLY THROUGHPUT=MID LATENCY=HIGH byte width=1 freq ratio=6 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=110 write_power=400 use4initializers=YES score=50  */
extern unsigned char _mem_pool_xSPI2_network[]; /* [1056]; */
/* global pool 7 is ? */
/* index=7 file postfix=xSPI1 name=hyperRAM offset=0x90000000  absolute_mode size=33554424 READ_WRITE THROUGHPUT=MID LATENCY=HIGH byte width=2 freq ratio=5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=ON read_power=380 write_power=340 use4initializers=YES score=82  */
/* global pool 1 is 48 B */
/* index=1 file postfix=AXISRAM5 name=npuRAM5 offset=0x342e0000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 2 is ? */
/* index=2 file postfix=AXISRAM4 name=npuRAM4 offset=0x34270000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 3 is ? */
/* index=3 file postfix=AXISRAM3 name=npuRAM3 offset=0x34200000  absolute_mode size=458752 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=18.531 write_power=16.201 use4initializers=NO score=94  */
/* global pool 0 is ? */
/* index=0 file postfix=AXISRAM6 name=npuRAM6 offset=0x34350000  absolute_mode size=458744 READ_WRITE THROUGHPUT=HIGH LATENCY=LOW byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=15.79 use4initializers=NO score=94  */
/* global pool 11 is 1.88 MB */
/* index=11 file postfix=AXISRAM2_AXISRAM3_AXISRAM4_AXISRAM5_AXISRAM6 name=cpuRAM2_npuRAM3_npuRAM4_npuRAM5_npuRAM6 offset=0x34100000  absolute_mode size=2883576 vpool READ_WRITE THROUGHPUT=HIGH LATENCY=MID byte width=8 freq ratio=1.25 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=19.006 write_power=16.201 use4initializers=NO score=91  */
/* global pool 4 is ? */
/* index=4 file postfix=AXISRAM2 name=cpuRAM2 offset=0x34100000  absolute_mode size=1048576 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=17.324 write_power=15.321 use4initializers=NO score=84  */
/* global pool 5 is ? */
/* index=5 file postfix=AXISRAM1 name=cpuRAM1 offset=0x34064000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=16.616 write_power=14.522 use4initializers=NO score=84  */
/* global pool 6 is ? */
/* index=6 file postfix=AXIFLEXMEM name=flexMEM offset=0x34000000  absolute_mode size=0 READ_WRITE THROUGHPUT=MID LATENCY=MID byte width=8 freq ratio=2.5 burst max length=MAXINT burst penalty=0 pipelined=ON cacheable=OFF read_power=9.381 write_power=8.569 use4initializers=NO score=84  */


const LL_Streng_EncryptionTypedef *LL_ATON_WeightEncryption_Info_network()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

const LL_Streng_EncryptionTypedef *LL_ATON_BlobEncryption_Info_network()
{
  static const LL_Streng_EncryptionTypedef LL_Streng_EncryptionStruct = {
    .enable = 0,
  };

  return &LL_Streng_EncryptionStruct;
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Input_Buffer_network(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Input_Buffer_network(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

LL_ATON_User_IO_Result_t LL_ATON_Set_User_Output_Buffer_network(uint32_t num, void* buffer, uint32_t size)
{
  LL_ATON_LIB_UNUSED(num);
  LL_ATON_LIB_UNUSED(buffer);
  LL_ATON_LIB_UNUSED(size);

  { 
    return LL_ATON_User_IO_WRONG_INDEX;
  }
}

void *LL_ATON_Get_User_Output_Buffer_network(uint32_t num)
{
  LL_ATON_LIB_UNUSED(num);

  { 
    return NULL;
  }
}

#include "network_ecblobs.h"

/* scheduling epoch=0    nodes=13  ------------------------------------------------------------------- */

// Epoch Controller Blob (name='_ec_blob_network_1') micro instructions needed

// Epoch Controller Blob (name='_ec_blob_network_1') start function
static void _ec_blob_cache_start_func_1(const LL_ATON_RT_EpochBlockItem_t *epoch_block, const NN_Instance_TypeDef *nn_instance) {
  LL_ATON_LIB_UNUSED(epoch_block);
  LL_ATON_LIB_UNUSED(nn_instance);

  /* *** MCU cache invalidate (only) operation (HW, whole range) *** */
  /*     memory pool: 1 */
  /*     start: ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) */
  /*     end:   ((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 32))) */
  LL_ATON_Cache_MCU_Invalidate_Range(((uintptr_t)(ATON_LIB_PHYSICAL_TO_VIRTUAL_ADDR(0x342e0000UL + 0))) /* Equivalent hex address = 0x342e0000UL */, 32);

};


/* scheduling DONE                 ------------------------------------------------------------------- */

const LL_ATON_RT_EpochBlockItem_t *LL_ATON_EpochBlockItems_network(void) {

  static const LL_ATON_RT_EpochBlockItem_t ll_atonn_rt_epoch_block_array[] = {
    {
      .start_epoch_block = _ec_blob_cache_start_func_1,
      .end_epoch_block = NULL,
      .blob_address = (uintptr_t)(_ec_blob_network_1_address),
      .wait_mask = 0,
      .flags = EpochBlock_Flags_epoch_start | EpochBlock_Flags_epoch_end | EpochBlock_Flags_blob | EpochBlock_Flags_pure_hw,
#ifdef LL_ATON_EB_DBG_INFO
      .epoch_num = 1,
      .last_epoch_num = 4,
      .estimated_npu_cycles = 683,
      .estimated_tot_cycles = 6240,
#endif // LL_ATON_EB_DBG_INFO
    },
    {
      .flags = EpochBlock_Flags_last_eb,
    },
  };


  return ll_atonn_rt_epoch_block_array;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Input_Buffers_Info_network(void)
{
  static const uint32_t buff_info__shape_1_16[] = { 1, 1, 16, 1 };
  static const uint32_t buff_info__mem_shape_U_1_16[] = { 1, 16 };
  static const float buff_info_Input_0_out_0_quant_scale[] = { 0.00415257783606648 };
  static const int16_t buff_info_Input_0_out_0_quant_offset[] = { -118 };
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const uint32_t buff_info__shape_32_16_1_1[] = { 32, 1, 1, 16 };
  static const uint32_t buff_info__mem_shape_F_32_16_1_1[] = { 32, 16, 1, 1 };
  static const float buff_info_Gemm_2_weights_transposed_3_quant_scale[] = { 0.00406252173706889, 0.00550072127953172, 0.00630606384947896, 0.00769104529172182, 0.00343611370772123, 0.00663100369274616, 0.00739920325577259, 0.00656764348968863, 0.00717439549043775, 0.00568761024624109, 0.00506677990779281, 0.00522536365315318, 0.00687337107956409, 0.00501734204590321, 0.00729536730796099, 0.0060050874017179, 0.00623862398788333, 0.00486579211428761, 0.00755043234676123, 0.00687185116112232, 0.00469634961336851, 0.00669347029179335, 0.00596230337396264, 0.00594584876671433, 0.00558195868507028, 0.00784081965684891, 0.00393322063609958, 0.00769861880689859, 0.00796023011207581, 0.00528964353725314, 0.00514850532636046, 0.00460234098136425 };
  static const int16_t buff_info_Gemm_2_weights_transposed_3_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_16_32_1_1[] = { 16, 1, 1, 32 };
  static const uint32_t buff_info__mem_shape_F_16_32_1_1[] = { 16, 32, 1, 1 };
  static const float buff_info_Gemm_6_weights_transposed_9_quant_scale[] = { 0.00810276065021753, 0.0135347144678235, 0.00413657631725073, 0.0196875371038914, 0.00780075648799539, 0.0170245710760355, 0.0126171950250864, 0.0151223307475448, 0.0218932945281267, 0.00490237819030881, 0.00641397712752223, 0.00674189301207662, 0.0132634798064828, 0.00432511791586876, 0.00735475029796362, 0.0180041715502739 };
  static const int16_t buff_info_Gemm_6_weights_transposed_9_quant_offset[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
  static const uint32_t buff_info__shape_1_16_1_1[] = { 1, 1, 1, 16 };
  static const uint32_t buff_info__mem_shape_F_1_16_1_1[] = { 1, 16, 1, 1 };
  static const float buff_info_Gemm_10_weights_transposed_15_quant_scale[] = { 0.0182544570416212 };
  static const int16_t buff_info_Gemm_10_weights_transposed_15_quant_offset[] = { 0 };
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Input_0_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 16,
      .offset_limit = 80,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 0,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1_16,
      .mem_ndims = 2,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_16,
      .per_channel = 0,
      .scale = buff_info_Input_0_out_0_quant_scale,
      .offset = buff_info_Input_0_out_0_quant_offset,
    },
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = "Gemm_2_weights_transposed_3",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 528,
      .offset_end = 1040,
      .offset_limit = 1104,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 16,
      .mem_shape = buff_info__mem_shape_F_32_16_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_32_16_1_1,
      .per_channel = 1,
      .scale = buff_info_Gemm_2_weights_transposed_3_quant_scale,
      .offset = buff_info_Gemm_2_weights_transposed_3_quant_offset,
    },
    {
      .name = "Gemm_6_weights_transposed_9",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 0,
      .offset_end = 513,
      .offset_limit = 584,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 32,
      .mem_shape = buff_info__mem_shape_F_16_32_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_16_32_1_1,
      .per_channel = 1,
      .scale = buff_info_Gemm_6_weights_transposed_9_quant_scale,
      .offset = buff_info_Gemm_6_weights_transposed_9_quant_offset,
    },
    {
      .name = "Gemm_10_weights_transposed_15",
      .addr_base = {(unsigned char *)ATON_LIB_VIRTUAL_TO_PHYSICAL_ADDR((uintptr_t)_mem_pool_xSPI2_network)},
      .offset_start = 1040,
      .offset_end = 1056,
      .offset_limit = 1120,
      .is_user_allocated = 0,
      .is_param = 1,
      .epoch = 0,
      .batch = 16,
      .mem_shape = buff_info__mem_shape_F_1_16_1_1,
      .mem_ndims = 4,
      .chpos = CHPos_First,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_16_1_1,
      .per_channel = 0,
      .scale = buff_info_Gemm_10_weights_transposed_15_quant_scale,
      .offset = buff_info_Gemm_10_weights_transposed_15_quant_offset,
    },
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Output_Buffers_Info_network(void)
{
  static const uint32_t buff_info__shape_1_1[] = { 1, 1, 1, 1 };
  static const uint32_t buff_info__mem_shape_U_1_1[] = { 1, 1 };
  static const float buff_info_Quantize_14_out_0_quant_scale[] = { 0.00390625 };
  static const int16_t buff_info_Quantize_14_out_0_quant_offset[] = { -128 };
  static const LL_Buffer_InfoTypeDef buff_info[] = {
    {
      .name = "Quantize_14_out_0",
      .addr_base = {(unsigned char *)(0x342e0000UL) /* Equivalent hex address = 0x342e0000UL */},
      .offset_start = 0,
      .offset_end = 1,
      .offset_limit = 72,
      .is_user_allocated = 0,
      .is_param = 0,
      .epoch = 3,
      .batch = 1,
      .mem_shape = buff_info__mem_shape_U_1_1,
      .mem_ndims = 2,
      .chpos = CHPos_UNDEFINED,
      .Qm = 7,
      .Qn = 0,
      .Qunsigned = 0,
      .type = DataType_INT8,
      .nbits = 8,
      .ndims = 4,
      .shape = buff_info__shape_1_1,
      .per_channel = 0,
      .scale = buff_info_Quantize_14_out_0_quant_scale,
      .offset = buff_info_Quantize_14_out_0_quant_offset,
    },
    {
      .name = NULL,
    }
  };

  return buff_info;
}

const LL_Buffer_InfoTypeDef *LL_ATON_Internal_Buffers_Info_network(void)
{
  return NULL;
}

