// auto-generated by pv_gen_test_vectors.m
#ifndef TEST_VECTORS_H
#define TEST_VECTORS_H
#include <stdint.h>

#define TV_N_SCAN 8
#define TV_COUNT  4

// uniform    G=[1000 1000 1000]  Vgmpp=53.77V (norm 0.8538)
static const uint16_t tv_adc_0[16] = {0,104,0,341,0,578,0,816,0,1053,1500,1290,1493,1528,1423,1765};
// one_shaded G=[1000  500 1000]  Vgmpp=35.15V (norm 0.5581)
static const uint16_t tv_adc_1[16] = {0,104,0,341,0,578,1501,816,1483,1053,952,1290,751,1528,749,1765};
// gradient   G=[ 200  600 1000]  Vgmpp=36.03V (norm 0.5722)
static const uint16_t tv_adc_2[16] = {0,104,0,341,1281,578,901,816,900,1053,575,1290,301,1528,299,1765};
// staircase  G=[ 300  600  900]  Vgmpp=35.74V (norm 0.5676)
static const uint16_t tv_adc_3[16] = {0,104,0,341,1131,578,901,816,900,1053,532,1290,451,1528,449,1765};

static const uint16_t* const tv_adc[TV_COUNT] = {tv_adc_0,tv_adc_1,tv_adc_2,tv_adc_3,};
static const float tv_vgmpp_norm[TV_COUNT] = {0.85381f,0.55809f,0.57220f,0.56755f,};

#endif
