
/* AUTOGENERATED DO NOT MODIFY */

/**
 ******************************************************************************
 * @file    stai_network.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Implementation of ST.AI platform public APIs for ATON
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __STAI_ATON_NETWORK_H
#define __STAI_ATON_NETWORK_H

// Include ATON runtime/library configuration file
#include "ll_aton_config.h"
#include "ll_aton_stai_internal.h"

// clang-format off
#ifdef __cplusplus
extern "C"
{
#endif

/*
 * NOTE: the beyond macro MUST be set to the same value when compiling the different ATON runtime/library, and
 *       AtoNN compiler generated files
 */
#if !defined(LL_ATON_DBG_BUFFER_INFO_EXCLUDED)
#define LL_ATON_DBG_BUFFER_INFO_EXCLUDED 0
#endif

// Derive alignment
#define _alignof(t)                                                                                                    \
  ((sizeof(t) > 1) ? offsetof(                                                                                         \
                         struct {                                                                                      \
                           char c;                                                                                     \
                           t x;                                                                                        \
                         },                                                                                            \
                         x)                                                                                            \
                   : 1)

// Include ST.AI headers
#include "stai_aton_common.h"

/*****************************************************************************/
#define STAI_NETWORK_CONTEXT_SIZE      ((stai_size)sizeof(_stai_aton_context))
#define STAI_NETWORK_CONTEXT_ALIGNMENT (_alignof(_stai_aton_context))

/*****************************************************************************/
STAI_API_DECLARE_BEGIN

/*****************************************************************************/
/* ST.AI API extensions are available */
#ifndef HAS_STAI_EXT
#define HAS_STAI_EXT
#endif // HAS_STAI_EXT

/*****************************************************************************/
/*  Network management APIs  */
STAI_API_ENTRY
stai_return_code stai_network_init(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_deinit(stai_network *network);

STAI_API_ENTRY
stai_return_code stai_network_run(stai_network *network, const stai_run_mode mode);

STAI_API_ENTRY
stai_return_code stai_network_train(stai_network *network, const stai_run_mode mode);

/*****************************************************************************/
/*  Getters APIs  */

// needed only for python bindings to query internal context byte size
STAI_API_ENTRY
static inline stai_size stai_network_get_context_size(void)
{
  return STAI_NETWORK_CONTEXT_SIZE;
}

STAI_API_ENTRY
stai_return_code stai_network_get_info(stai_network *network, stai_network_info *info);

STAI_API_ENTRY
stai_return_code stai_network_get_inputs(stai_network *network, stai_ptr *inputs, stai_size *n_inputs);

STAI_API_ENTRY
stai_return_code stai_network_get_weights(stai_network *network, stai_ptr *weights, stai_size *n_weights);

STAI_API_ENTRY
stai_return_code stai_network_get_outputs(stai_network *network, stai_ptr *outputs, stai_size *n_outputs);

STAI_API_ENTRY
stai_return_code stai_network_get_activations(stai_network *network, stai_ptr *activations,
                                                            stai_size *n_activations);

STAI_API_ENTRY
stai_return_code stai_network_get_states(stai_network *network, stai_ptr *states, stai_size *n_states);
STAI_API_ENTRY
stai_return_code stai_network_get_error(stai_network *network);

/*****************************************************************************/
/*  Setters APIs  */

/**
 * @brief Set array of input buffers
 * @param network NN for which to set the input buffers
 * @param inputs array of input buffer pointers
 * @param n_inputs number of elements in the input buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_inputs(stai_network *network, const stai_ptr *inputs,
                                                       const stai_size n_inputs);

/**
 * @brief Set array of weight buffers
 * @param network NN for which to set the weight buffers
 * @param weights array of weight buffer pointers
 * @param n_weights number of elements in the weight buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for weights
 */
STAI_API_ENTRY
stai_return_code stai_network_set_weights(stai_network *network, const stai_ptr *weights,
                                                        const stai_size n_weights);

/**
 * @brief Set array of output buffers
 * @param network NN for which to set the output buffers
 * @param outputs array of output buffer pointers
 * @param n_outputs number of elements in the output buffer array
 * @return ST.AI error code
 *
 * @note for user allocatable buffers it is necessary that the effectively allocated memory comprises
 *       bottom & top paddings (where necessary) that allow for both the real buffer start address and the
 *       allocated size beyond this real start address to be aligned with the user buffer alignment macro
 *       (`STAI_CACHE_USER_BUFFER_ALIGNMENT`)
 */
STAI_API_ENTRY
stai_return_code stai_network_set_outputs(stai_network *network, const stai_ptr *outputs,
                                                        const stai_size n_outputs);

/**
 * @brief Set array of activation buffers
 * @param network NN for which to set the activation buffers
 * @param activations array of activation buffer pointers
 * @param n_activations number of elements in the activation buffer array
 * @return ST.AI error code
 *
 * @note user allocatable buffers are not supported for activations
 */
STAI_API_ENTRY
stai_return_code stai_network_set_activations(stai_network *network, const stai_ptr *activations,
                                                            const stai_size n_activations);

STAI_API_ENTRY
stai_return_code stai_network_set_states(stai_network *network, const stai_ptr *states,
                                                       const stai_size n_states);

STAI_API_ENTRY
stai_return_code stai_network_set_callback(stai_network *network, const stai_event_cb cb,
                                                         void *cb_cookie);

/***************************************************************************/
/*  Extended ATON Target Specific APIs  */

/** Asynchronous Execution **/
/**
 * @brief Continue network execution of an asynchronously started/run network
 *        (i.e. network was started/run in `stai_run_mode::STAI_MODE_ASYNC` mode)
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finished.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network opaque pointer
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_run_continue(stai_network *network);

/**
 * @brief Get execution status of a network
 * @details Running a network in asynchronous mode (see function `stai_network_run()` and its
 *          parameter `mode` being equal to `stai_run_mode::STAI_MODE_ASYNC`) means that
 *          `stai_network_run()` returns while the network is still in execution. In this case
 *          the user may not call `stai_network_run()` again until the network's execution has
 *          actually finish.
 *          Therefore, we need to have two new API functions, one that provides the execution status of the
 *          network `stai_ext_network_get_nn_run_status()`,
 *          and one which triggers the continuation of the network execution
 *          `stai_ext_network_run_continue()`.
 * @details While the asynchronously started network is in execution the user may call any application specific code.
 *          When she/he has finished to do so she/he should call `stai_ext_network_get_nn_run_status()`
 *          and act as follows with respect to its different return values:
 *          - `STAI_RUNNING_NO_WFE`: network is still running and `stai_ext_network_run_continue()` must
 *            be called (without calling `stai_ext_wfe()` before)
 *          - `STAI_RUNNING_WFE`: network is still running and `stai_ext_wfe()` should be called before calling
 *            `stai_ext_network_run_continue()`.
 *            NOTE, that in this case no other network instance may be run/continued from within the same thread!
 *            It is entirely the user's responsibility to comply with this restriction!
 *          - `STAI_DONE`: network execution has finished (do NOT call `stai_ext_network_run_continue()`
 * again)
 * @param[in] network network handle
 * @return error or execution status (i.e. `STAI_RUNNING_NO_WFE`, `STAI_RUNNING_WFE`, or `STAI_DONE`) return value
 *
 * @note enum `stai_return_code` might need to be extended to better represent errors of new API functions,
 *       in this case e.g. an enum value specifying that the provided network handle does not identify the currently
 *       running network, and one that informs about a still running network execution (for function
 *       `stai_network_run()`).
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_get_nn_run_status(stai_network *network);

/**
 * @brief Prepare the network for a new inference
 * @details In case `stai_ext_network_get_nn_run_status()` returns either `STAI_DONE` or
 *          `STAI_RUNNING_NO_WFE` (when called by the thread which actually executes the inference of the passed
 *          `network`), prepare `network` for another/new inference run.
 * @param[in] network network handle
 * @return
 *
 * @note May only be called by the thread actually executing the inference of `network`!
 * @note Necessary only in case current inference is/has been executed asynchronously!
 */
STAI_API_ENTRY
stai_return_code stai_ext_network_new_inference(stai_network *network);

/*****************************************************************************/
STAI_API_DECLARE_END

/*****************************************************************************/
#define STAI_NETWORK_STATES_NUM  (0)
#define STAI_NETWORK_STATES_SIZE (0)

/*****************************************************************************/
/************************** SUBSTITUTABLE section ****************************/
/*****************************************************************************/

/**************************** Cache line size(s) *****************************/
#ifndef STAI_CACHE_MCU_LINESIZE
#define STAI_CACHE_MCU_LINESIZE (32)
#elif (STAI_CACHE_MCU_LINESIZE != 32)
#error "MCU cache line size mismatch"
#endif

/* NPU cache extension is available */
#ifndef STAI_EXT_CACHE_HAS_NPU
#define STAI_EXT_CACHE_HAS_NPU
#endif
#define STAI_NETWORK_EXT_CACHE_HAS_NPU

#ifndef STAI_EXT_CACHE_NPU_LINESIZE
#define STAI_EXT_CACHE_NPU_LINESIZE (64)
#elif (STAI_EXT_CACHE_NPU_LINESIZE != 64)
#error "NPU cache line size mismatch"
#endif

#ifndef STAI_CACHE_USER_BUFFER_ALIGNMENT
#define STAI_CACHE_USER_BUFFER_ALIGNMENT STAI_CACHE_MCU_LINESIZE  // NOTE: user allocated buffers are assumed not to be NPU cacheable!
#endif

/********************************** INPUTS ***********************************/
#define STAI_NETWORK_IN_NUM (1)
#define STAI_NETWORK_IN_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_NETWORK_IN_NAMES \
  { \
    "Input_0_out_0" \
  }
#define STAI_NETWORK_IN_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_IN_SIZES \
  { \
    16 \
  }
#define STAI_NETWORK_IN_SIZES_BYTES \
  { \
    16 \
  }

#define STAI_NETWORK_IN_1_ALIGNMENT (32)
#define STAI_NETWORK_IN_1_NAME "Input_0_out_0"
#define STAI_NETWORK_IN_1_FLAGS (STAI_FLAG_PREALLOCATED)
#define STAI_NETWORK_IN_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_IN_1_SIZE (16)
#define STAI_NETWORK_IN_1_SIZE_BYTES (16)
#define STAI_NETWORK_IN_1_CHANNEL (1)
#define STAI_NETWORK_IN_1_HEIGHT (1)
#define STAI_NETWORK_IN_1_WIDTH (16)
#define STAI_NETWORK_IN_1_RANK (2)
#define STAI_NETWORK_IN_1_SHAPE \
  { \
    1, 16 \
  }
#define STAI_NETWORK_IN_1_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_IN_1_SCALES \
  { \
    0.00415257783606648 \
  }
#define STAI_NETWORK_IN_1_OFFSETS \
  { \
    -118 \
  }

/********************************** OUTPUTS **********************************/
#define STAI_NETWORK_OUT_NUM (1)
#define STAI_NETWORK_OUT_ALIGNMENTS \
  { \
    32 \
  }
#define STAI_NETWORK_OUT_NAMES \
  { \
    "Quantize_14_out_0" \
  }
#define STAI_NETWORK_OUT_FORMATS \
  { \
    STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_OUT_SIZES \
  { \
    1 \
  }
#define STAI_NETWORK_OUT_SIZES_BYTES \
  { \
    1 \
  }

#define STAI_NETWORK_OUT_1_ALIGNMENT (32)
#define STAI_NETWORK_OUT_1_NAME "Quantize_14_out_0"
#define STAI_NETWORK_OUT_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_OVERRIDE)
#define STAI_NETWORK_OUT_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_OUT_1_SIZE (1)
#define STAI_NETWORK_OUT_1_SIZE_BYTES (1)
#define STAI_NETWORK_OUT_1_CHANNEL (1)
#define STAI_NETWORK_OUT_1_HEIGHT (1)
#define STAI_NETWORK_OUT_1_WIDTH (1)
#define STAI_NETWORK_OUT_1_RANK (2)
#define STAI_NETWORK_OUT_1_SHAPE \
  { \
    1, 1 \
  }
#define STAI_NETWORK_OUT_1_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_OUT_1_SCALES \
  { \
    0.00390625 \
  }
#define STAI_NETWORK_OUT_1_OFFSETS \
  { \
    -128 \
  }

/********************************** WEIGHTS **********************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_NETWORK_WEIGHTS_NUM (3)
#define STAI_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
    16, 32, 16 \
  }
#define STAI_NETWORK_WEIGHTS_NAMES \
  { \
    "Gemm_2_weights_transposed_3", "Gemm_6_weights_transposed_9", "Gemm_10_weights_transposed_15" \
  }
#define STAI_NETWORK_WEIGHTS_FORMATS \
  { \
    STAI_FORMAT_S8, STAI_FORMAT_S8, STAI_FORMAT_S8 \
  }
#define STAI_NETWORK_WEIGHTS_SIZES \
  { \
    512, 512, 16 \
  }
#define STAI_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
    512, 512, 16 \
  }

#define STAI_NETWORK_WEIGHTS_1_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_1_NAME "Gemm_2_weights_transposed_3"
#define STAI_NETWORK_WEIGHTS_1_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_1_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_1_SIZE (512)
#define STAI_NETWORK_WEIGHTS_1_SIZE_BYTES (512)
#define STAI_NETWORK_WEIGHTS_1_CHANNEL (16)
#define STAI_NETWORK_WEIGHTS_1_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_1_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_1_BATCH (16)
#define STAI_NETWORK_WEIGHTS_1_RANK (4)
#define STAI_NETWORK_WEIGHTS_1_SHAPE \
  { \
    32, 1, 1, 16 \
  }
#define STAI_NETWORK_WEIGHTS_1_SCALE_OFFSET_NUM (32)
#define STAI_NETWORK_WEIGHTS_1_SCALES \
  { \
    0.00406252173706889, 0.00550072127953172, 0.00630606384947896, 0.00769104529172182, 0.00343611370772123, 0.00663100369274616, 0.00739920325577259, 0.00656764348968863, 0.00717439549043775, 0.00568761024624109, 0.00506677990779281, 0.00522536365315318, 0.00687337107956409, 0.00501734204590321, 0.00729536730796099, 0.0060050874017179, 0.00623862398788333, 0.00486579211428761, 0.00755043234676123, 0.00687185116112232, 0.00469634961336851, 0.00669347029179335, 0.00596230337396264, 0.00594584876671433, 0.00558195868507028, 0.00784081965684891, 0.00393322063609958, 0.00769861880689859, 0.00796023011207581, 0.00528964353725314, 0.00514850532636046, 0.00460234098136425 \
  }
#define STAI_NETWORK_WEIGHTS_1_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_2_ALIGNMENT (32)
#define STAI_NETWORK_WEIGHTS_2_NAME "Gemm_6_weights_transposed_9"
#define STAI_NETWORK_WEIGHTS_2_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_2_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_2_SIZE (512)
#define STAI_NETWORK_WEIGHTS_2_SIZE_BYTES (512)
#define STAI_NETWORK_WEIGHTS_2_CHANNEL (32)
#define STAI_NETWORK_WEIGHTS_2_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_2_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_2_BATCH (32)
#define STAI_NETWORK_WEIGHTS_2_RANK (4)
#define STAI_NETWORK_WEIGHTS_2_SHAPE \
  { \
    16, 1, 1, 32 \
  }
#define STAI_NETWORK_WEIGHTS_2_SCALE_OFFSET_NUM (16)
#define STAI_NETWORK_WEIGHTS_2_SCALES \
  { \
    0.00810276065021753, 0.0135347144678235, 0.00413657631725073, 0.0196875371038914, 0.00780075648799539, 0.0170245710760355, 0.0126171950250864, 0.0151223307475448, 0.0218932945281267, 0.00490237819030881, 0.00641397712752223, 0.00674189301207662, 0.0132634798064828, 0.00432511791586876, 0.00735475029796362, 0.0180041715502739 \
  }
#define STAI_NETWORK_WEIGHTS_2_OFFSETS \
  { \
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 \
  }

#define STAI_NETWORK_WEIGHTS_3_ALIGNMENT (16)
#define STAI_NETWORK_WEIGHTS_3_NAME "Gemm_10_weights_transposed_15"
#define STAI_NETWORK_WEIGHTS_3_FLAGS (STAI_FLAG_PREALLOCATED|STAI_FLAG_CHANNEL_LAST)
#define STAI_NETWORK_WEIGHTS_3_FORMAT (STAI_FORMAT_S8)
#define STAI_NETWORK_WEIGHTS_3_SIZE (16)
#define STAI_NETWORK_WEIGHTS_3_SIZE_BYTES (16)
#define STAI_NETWORK_WEIGHTS_3_CHANNEL (16)
#define STAI_NETWORK_WEIGHTS_3_HEIGHT (1)
#define STAI_NETWORK_WEIGHTS_3_WIDTH (1)
#define STAI_NETWORK_WEIGHTS_3_BATCH (16)
#define STAI_NETWORK_WEIGHTS_3_RANK (4)
#define STAI_NETWORK_WEIGHTS_3_SHAPE \
  { \
    1, 1, 1, 16 \
  }
#define STAI_NETWORK_WEIGHTS_3_SCALE_OFFSET_NUM (1)
#define STAI_NETWORK_WEIGHTS_3_SCALES \
  { \
    0.0182544570416212 \
  }
#define STAI_NETWORK_WEIGHTS_3_OFFSETS \
  { \
    0 \
  }
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_NETWORK_WEIGHTS_NUM (0)
#define STAI_NETWORK_WEIGHTS_ALIGNMENTS \
  { \
  }
#define STAI_NETWORK_WEIGHTS_NAMES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_FORMATS \
  { \
  }
#define STAI_NETWORK_WEIGHTS_SIZES \
  { \
  }
#define STAI_NETWORK_WEIGHTS_SIZES_BYTES \
  { \
  }
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0

/******************************** ACTIVATIONS ********************************/
#define STAI_NETWORK_ACTIVATIONS_NUM (0)
#define STAI_NETWORK_ACTIVATIONS_ALIGNMENTS \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_NAMES \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_FORMATS \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_SIZES \
  { \
  }
#define STAI_NETWORK_ACTIVATIONS_SIZES_BYTES \
  { \
  }

/****************************** NETWORK MACROS *******************************/
#if LL_ATON_DBG_BUFFER_INFO_EXCLUDED != 0
#define STAI_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS)
#else  // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0
#define STAI_NETWORK_FLAGS (STAI_FLAG_INPUTS|STAI_FLAG_OUTPUTS|STAI_FLAG_WEIGHTS)
#endif // LL_ATON_DBG_BUFFER_INFO_EXCLUDED == 0

#define STAI_NETWORK_ORIGIN_MODEL_NAME "gmpp_model_int8_OE_3_3_1"
#define STAI_NETWORK_C_MODEL_NAME "network"

/*************************** RELATIVE MEMORY POOLS ***************************/
extern unsigned char _mem_pool_xSPI2_network[];

#ifdef __cplusplus
}
#endif

#endif // __STAI_ATON_NETWORK_H
